baseURL = 'https://linuxcnc-ethercat.github.io/'
languageCode = 'en-us'
title = 'LinuxCNC-Ethercat Documentation'

theme ="linuxcnc-ethercat-theme"

pygmentsUseClasses = true
pygmentsCodefences = true

enableEmoji = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'onedark'
    tabWidth = 4


